
### 登录
# @name=123
GET http://127.0.0.1:3000/oauth2/authorize?response_type=code&client_id=app&scope=server&redirect_uri=http://localhost:4040/sso1/login&continue
Accept: text/html
# Cookie: JSESSIONID=MeJUcYDi-noxyu_2ZZb0a12eT5kcJtTSAflIZxpf; 


### 登录
POST http://127.0.0.1:3000/oauth2/form
Cookie: JSESSIONID=2XEgQuDD01wD_O76ay32Lp9lx68i94Tk0UopOxp2;
Content-Type: application/x-www-form-urlencoded

client_id=pig&grant_type=password&username=admin&password=123456


### 登录（网关）
# 登录页跳转，这一步会生成 session，保存之前的请求信息（比如回调地址）
GET http://127.0.0.1:9999/auth/oauth2/authorize?response_type=code&client_id=app&scope=server&redirect_uri=http://localhost:4040/sso1/login
Accept: text/html
Cookie: SESSION=MTQ2N2ZmM2ItNjNlMS00YjQ5LThiMTEtYmM4YjU1ZDY4Y2Rm;


### 登录（网关）
### 模拟统一认证平台登录
POST http://127.0.0.1:9999/auth/oauth2/form
Cookie: SESSION=MTQ2N2ZmM2ItNjNlMS00YjQ5LThiMTEtYmM4YjU1ZDY4Y2Rm;
Content-Type: application/x-www-form-urlencoded

client_id=pig&grant_type=password&username=admin&password=123456

### GET
### 统一认证平台登录后跳转到授权地址，之前已经登录过了，所以会认证通过，然后根据之前保存的请求信息重定向到回调地址
GET http://127.0.0.1:9999/auth/oauth2/authorize?response_type=code&client_id=app&scope=server&redirect_uri=http://localhost:4040/sso1/login
Cookie: SESSION=ODJkMzUxNTUtOWRjNS00ZmJhLWI4ZTItZDI3YTA2Mzg1N2Mw;
Accept: text/html


### 获取 token (authorization_code)
POST http://127.0.0.1:9999/auth/oauth2/token
Authorization: Basic YXBwOmFwcA==
Content-Type: application/x-www-form-urlencoded

grant_type=authorization_code&scope=server&redirect_uri=http://localhost:4040/sso1/login&code=kGRFhlTcAg4LB6n8qGhbJF9JtvyOW5cmPtobHPU9cwDISYvMxQd036arTjpJdHxGnrTgHCiIL7U85SAgwfCmX3VU2JZV2vM4_EWPIWeZAdub9jkqrlFMVzWEL2H37HeA


### 请求验证码
GET http://127.0.0.1:9999/auth/code/image?randomStr=c136de0f-dcf2-428c-ba0f-5c9640afd22b HTTP/1.1
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36
Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Accept-Language: en,zh-CN;q=0.9,zh;q=0.8
Connection: keep-alive
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: same-origin
Sec-Ch-Ua: "Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Host: localhost:8888

### 获取 token (password)
POST http://127.0.0.1:9999/auth/oauth2/token HTTP/1.1
Authorization: Basic cGlnOnBpZw==
Connection: keep-alive
Content-Type: application/x-www-form-urlencoded
Origin: http://localhost:8888
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Sec-Ch-Ua: "Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Skiptoken: true
Content-Length: 119

username=admin&password=YehdBPev&code=2&randomStr=c136de0f-dcf2-428c-ba0f-5c9640afd22b&grant_type=password&scope=server

### 测试 refresh token
POST http://127.0.0.1:9999/auth/oauth2/token HTTP/1.1
Authorization: Basic YXBwOmFwcA==
Content-Type: application/x-www-form-urlencoded

grant_type=refresh_token&refresh_token=1QNelVmG7xiLIKaEYQ0lqHMJVuO_ydzmJ7vOOabqrh20-QGCOjwx5uNupT3Ni_3rWoCdzRkL0eiqxdlIh7MlbSCBZ--ilkOrXOC2lsd-SZFyD4AaBfmddMn1MYS-JJPP



### 测试
GET /api/admin/user/info HTTP/1.1
Cookie: token=6ickx2pBzQw_9_Ow_rrbOp-BAKtukM0D9xsGmwQdbdghe5Dg_NHgTJ1iyvV9iG1a0aTEsBpVUUem8zEq2BNsTi_Y5XouFyfzolKB8lpbO4WzoWnu_gUqLJQak5J2x-Cq; refresh_token=kB6_9qcKY6_7zujvowj1gkE2qWVd0WWXDOqbEQjFOOqVyMsptp4C6lWVF4dXEiwk-Xvvm9-MIkKV-oHEbuJbxdH3mjUtusp9l6dQKhW_02X9EmNCX0Nc0TBEcy2xG5qW
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/143.0.0.0 Safari/537.36
Accept: application/json, text/plain, */*
Accept-Language: en,zh-CN;q=0.9,zh;q=0.8
Authorization: Bearer 6ickx2pBzQw_9_Ow_rrbOp-BAKtukM0D9xsGmwQdbdghe5Dg_NHgTJ1iyvV9iG1a0aTEsBpVUUem8zEq2BNsTi_Y5XouFyfzolKB8lpbO4WzoWnu_gUqLJQak5J2x-Cq
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Sec-Ch-Ua: "Google Chrome";v="143", "Chromium";v="143", "Not A(Brand";v="24"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Host: localhost:8888

